---
Name: focuspoint
After:
    - 'assetsimage'
---
SilverStripe\Assets\Image:
  extensions:
    - JonoM\FocusPoint\FocusPointImageExtension
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - JonoM\FocusPoint\FocusPointImageExtension
SilverStripe\AssetAdmin\Forms\AssetFormFactory:
  extensions:
    - JonoM\FocusPoint\FocusPointAssetFormFactoryExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'jonom/focuspoint: client/css/FocusPointField.css'
  extra_requirements_javascript:
    - 'jonom/focuspoint: client/javascript/FocusPointField.js'
# SilverStripe\Core\Injector\Injector:
#   SilverStripe\Assets\Image_Backend:
#     class: JonoM\FocusPoint\InterventionBackend